language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - cd udagram-api

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api .
  - docker tag udagram-api ucast84/udagram-api:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ucast84/udagram-api

