apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
    spec:
      containers:
      - name: udagram-frontend
        image: ucast84/udagram-frontend
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"         
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true                           
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret      