apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-1
  labels:
    app: api-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app-1
  template:
    metadata:
      labels:
        app: api-app-1
    spec:
      containers:
      - name: udagram-api
        image: ucast84/udagram-api
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v0
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 20
